version: '3.8'

services:
  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: securepay-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://api-gateway:8080
    depends_on:
      - api-gateway
    networks:
      - securepay-network
    restart: unless-stopped

  # API Gateway Service
  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    container_name: securepay-api-gateway
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8081
      - PAYMENT_SERVICE_URL=http://payment-service:8082
      - SUBSCRIPTION_SERVICE_URL=http://subscription-service:8083
      - ANALYTICS_SERVICE_URL=http://analytics-service:8084
      - NOTIFICATION_SERVICE_URL=http://notification-service:8085
      - FRAUD_SERVICE_URL=http://fraud-service:8086
      - JWT_SECRET=${JWT_SECRET:-securepay_jwt_secret_key}
    depends_on:
      - auth-service
      - payment-service
      - subscription-service
      - analytics-service
      - notification-service
      - fraud-service
    networks:
      - securepay-network
    restart: unless-stopped

  # Auth Service
  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    container_name: securepay-auth-service
    ports:
      - "8081:8081"
    environment:
      - JWT_SECRET=${JWT_SECRET:-securepay_jwt_secret_key}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=securepay
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - securepay-network
    restart: unless-stopped

  # Payment Service
  payment-service:
    build:
      context: ./backend/payment-service
      dockerfile: Dockerfile
    container_name: securepay-payment-service
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=securepay
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - securepay-network
    restart: unless-stopped

  # Subscription Management Service
  subscription-service:
    build:
      context: ./backend/subscription-service
      dockerfile: Dockerfile
    container_name: securepay-subscription-service
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=securepay
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - securepay-network
    restart: unless-stopped

  # Analytics Service
  analytics-service:
    build:
      context: ./backend/analytics-service
      dockerfile: Dockerfile
    container_name: securepay-analytics-service
    ports:
      - "8084:8084"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=securepay
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - securepay-network
    restart: unless-stopped

  # Notification Service
  notification-service:
    build:
      context: ./backend/notification-service
      dockerfile: Dockerfile
    container_name: securepay-notification-service
    ports:
      - "8085:8085"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=securepay
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - securepay-network
    restart: unless-stopped

  # Fraud Detection Service
  fraud-service:
    build:
      context: ./backend/fraud-service
      dockerfile: Dockerfile
    container_name: securepay-fraud-service
    ports:
      - "8086:8086"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=securepay
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - securepay-network
    restart: unless-stopped

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=securepay
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - securepay-network

networks:
  securepay-network:
    driver: bridge

volumes:
  postgres-data: 